In [2]:
import numpy as np
import pandas as pd

n_data = 1000

# Menghasilkan data
usia = np.random.randint(18, 61, size=n_data)
gender = np.random.randint(0, 2, size=n_data) # 0 untuk perempuan, 1 untuk laki-laki
gaji = np.random.randint(3000, 15000, size=n_data) 
tingkat_pendidikan = np.random.choice(['SMA', 'D3', 'S1', 'S2'], size=n_data)
tahun_pengalaman = np.random.randint(0, usia - 17)
skor_kinerja = np.random.randint(0, 101, size=n_data)
dept = np.random.choice(['IT', 'HR', 'Finance', 'Marketing', 'Production'], size=n_data)
city = np.random.choice(['Bogor', 'Bandung', 'Sukabumi', 'Karawang', 'Bekasi'], size=n_data)
produktivitas = np.clip(np.random.normal(75, 10, size=n_data), 0, 100).round(2)

# Buat dataframe
df = pd.DataFrame({
    'Usia': usia,
    'Gender': gender,
    'Gaji': gaji,
    'Tingkat Pendidikan': tingkat_pendidikan,
    'Pengalaman Kerja': tahun_pengalaman,
    'Skor Kinerja': skor_kinerja,
    'Departemen': dept,
    'Kota': city,
    'Produktivitas': produktivitas
})

#Menampilkan isi data
print("\n=== Informasi Data ===")
print(df.info())

print("\n=== Lima Baris Pertama ===")
print(df.head())

#Menganalisis data
print("\n=== Distribusi Gender ===")
print(df['Gender'].value_counts())

print("\n=== Distribusi Tingkat Pendidikan ===")
print(df['Tingkat Pendidikan'].value_counts())

print("\n=== Distribusi Departemen ===")
print(df['Departemen'].value_counts())

print("\n=== Distribusi Kota ===")
print(df['Kota'].value_counts())

print("\n=== Rata-rata Produktivitas per Departemen ===")
print(df.groupby('Departemen')['Produktivitas'].mean())

print("\n=== Rata-rata Gaji berdasarkan Tingkat Pendidikan ===")
print(df.groupby('Tingkat Pendidikan')['Gaji'].mean())

print("\n=== Rata-rata Produktivitas berdasarkan Gender ===")
print(df.groupby('Gender')['Produktivitas'].mean())

df.to_csv('dataKaryawan.csv')

=== Informasi Data ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Usia                1000 non-null   int32
 1   Gender              1000 non-null   int32
 2   Gaji                1000 non-null   int32
 3   Tingkat Pendidikan  1000 non-null   object
 4   Pengalaman Kerja    1000 non-null   int32
 5   Skor Kinerja        1000 non-null   int32
 6   Departemen          1000 non-null   object
 7   Kota                1000 non-null   object
 8   Produktivitas       1000 non-null   float64
dtypes: float64(1), int32(5), object(3)
memory usage: 50.9+ KB
None

=== Lima Baris Pertama ===
   Usia  Gender   Gaji Tingkat Pendidikan  Pengalaman Kerja  Skor Kinerja  \
0    51       0   5247                 S1                 6            89
1    46       0   5435                SMA                24            26
2    44       0  10356                 S1                25            60
3    53       0  11184                SMA                 5            58
4    32       0   4170                 S1                13            80

   Departemen      Kota  Produktivitas
0     Finance  Sukabumi          57.47
1          IT  Karawang          71.02
2     Finance  Karawang          63.61
3   Marketing   Bandung          74.31
4  Production  Karawang          70.08

=== Distribusi Gender ===
Gender
0    501
1    499
Name: count, dtype: int64

=== Distribusi Tingkat Pendidikan ===
Tingkat Pendidikan
SMA    263
S2     258
S1     244
D3     235
Name: count, dtype: int64

=== Distribusi Departemen ===
Departemen
Marketing     220
Finance       204
Production    195
IT            193
HR            188
Name: count, dtype: int64

=== Distribusi Kota ===
Kota
Bekasi      213
Bogor       204
Sukabumi    203
Bandung     197
Karawang    183
Name: count, dtype: int64

=== Rata-rata Produktivitas per Departemen ===
Departemen
Finance       75.526765
HR            74.555160
IT            74.076010
Marketing     74.761409
Production    73.540974
Name: Produktivitas, dtype: float64

=== Rata-rata Gaji berdasarkan Tingkat Pendidikan ===
Tingkat Pendidikan
D3     8884.595745
S1     8543.500000
S2     9070.813953
SMA    8825.338403
Name: Gaji, dtype: float64

=== Rata-rata Produktivitas berdasarkan Gender ===
Gender
0    74.424810
1    74.592525
Name: Produktivitas, dtype: float64